// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyCsdJD24gJxGLyQSwYEitfF8WH6WXi8NYI",
    authDomain: "movie-app-177f3.firebaseapp.com",
    projectId: "movie-app-177f3",
    storageBucket: "movie-app-177f3.firebasestorage.app",
    messagingSenderId: "855182118487",
    appId: "1:855182118487:web:1113453ef410ae4d921d12",
    measurementId: "G-TQSWRZYMXE",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6hW9q3RxW9kst6dn-5UY19dWLrpnNDKc',
    appId: '1:855182118487:android:2b7b8bbac060cedb921d12',
    messagingSenderId: '855182118487',
    projectId: 'movie-app-177f3',
    storageBucket: 'movie-app-177f3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6hW9q3RxW9kst6dn-5UY19dWLrpnNDKc',
    appId: '1:855182118487:ios:2b7b8bbac060cedb921d12',
    messagingSenderId: '855182118487',
    projectId: 'movie-app-177f3',
    storageBucket: 'movie-app-177f3.firebasestorage.app',
    iosBundleId: 'com.example.movie-app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6hW9q3RxW9kst6dn-5UY19dWLrpnNDKc',
    appId: '1:855182118487:ios:2b7b8bbac060cedb921d12',
    messagingSenderId: '855182118487',
    projectId: 'movie-app-177f3',
    storageBucket: 'movie-app-177f3.firebasestorage.app',
    iosBundleId: 'com.example.movie-app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6hW9q3RxW9kst6dn-5UY19dWLrpnNDKc',
    appId: '1:855182118487:windows:2b7b8bbac060cedb921d12',
    messagingSenderId: '855182118487',
    projectId: 'movie-app-177f3',
    storageBucket: 'movie-app-177f3.firebasestorage.app',
  );
}
